/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cx_testndkdemo_MainActivity */

#ifndef _Included_com_cx_testndkdemo_MainActivity
#define _Included_com_cx_testndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cx_testndkdemo_MainActivity
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_testndkdemo_MainActivity_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
